name: exchangilymobileapp
description: Decentralized Wallet App.

version: 1.1.7+30

environment:
  sdk: '>=2.3.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # Cupertino Icons
  cupertino_icons: ^0.1.2

  # Bip39
  bip39: ^1.0.3
  bs58check: ^1.0.1
  # bitcoin Flutter
  bitcoin_flutter: ^1.0.7

  # Pointy Castle
  # pointycastle: ^1.0.1

  # Encrypt
  encrypt: ^3.3.0

  # Logger
  logger: ^0.6.0

  # Web 3 Dart
  web3dart: ^1.2.1

  # Http
  http: ^0.12.0+2

  # Rxdart
  rxdart: ^0.22.0

  # Font Awesome
  font_awesome_flutter: 8.8.0

  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.0.1

  # Pattern Formatter
  pattern_formatter: ^1.0.0

  # Path Provider
  path_provider: 1.4.2
  random_string: ^2.0.1
  # Keccak
  keccak: ^1.0.3

  # Web Sockets
  web_socket_channel: ^1.1.0

  # Json Serialization
  json_serializable: ^2.2.1

  # Generate QR Code Image
  qr_flutter: ^3.1.0
  qr: 1.2.0

  # Barcode Scan
  barcode_scan: 1.0.0

  # Flushbar instead of Snackbar for notifications
  #flushbar: ^1.9.0
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master
  decimal: ^0.3.5

  # Dependency injection
  get_it: ^1.0.3

  # Device Preview
  device_preview:
  webview_flutter: ^0.3.19+4

  # rflutter Alert
  rflutter_alert: ^1.0.3

  # Shared Preferences
  shared_preferences: ^0.5.6+1

  # Loading animation
  shimmer: ^1.0.1

  # Local DB
  sqflite: ^1.3.0

  # Path
  path: ^1.6.4

  # Build version
  package_info: 0.4.0+16

  # Pull to refresh
  pull_to_refresh: ^1.5.7

  # Flutter SVG
  flutter_svg: ^0.17.3+1

  # State Management
  stacked: ^1.5.4

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

dev_dependencies:
  intl_translation: '^0.17.0'
  intl: ^0.16.1
  flutter_launcher_icons: '^0.7.3'

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # module:
  #   androidX: true
  #   androidPackage: my.package
  #   iosBundleIdentifier: my.package
  assets:
    - assets/images/start-page/
    - assets/images/wallet-page/
    - assets/images/otc/
    - assets/images/otc-campaign/
    - assets/pages/index.html
flutter_icons:
  image_path: 'assets/images/launcher/mobile-icon.png'
  android: true
  ios: true

fonts:
  - family: Roboto
    fonts:
      - asset: Roboto-Italic.ttf
      - asset: Roboto-normal.ttf
  #  - lib/l10n/en.json
  #  - lib/l10n/zh.json
