name: exchangilymobileapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # Cupertino Icons
  cupertino_icons: ^0.1.2

  # Bip39
  bip39: ^1.0.3

  # bitcoin Flutter
  bitcoin_flutter: ^1.0.7

  # Pointy Castle
  # pointycastle: ^1.0.1

  # Encrypt
  encrypt: ^3.3.0

  # Logger
  logger: ^0.7.0+2

  # Web 3 Dart
  web3dart: ^1.2.1

  # Http
  http: ^0.12.0+2

  # Rxdart
  rxdart: ^0.22.0

  # Font Awesome
  font_awesome_flutter: 8.4.0

  # Provider
  provider: 3.1.0+1

  # Pattern Formatter
  pattern_formatter: ^1.0.0

  # Path Provider
  path_provider: 1.4.2

  # Keccak
  keccak: ^1.0.3

  # Web Sockets
  web_socket_channel: ^1.1.0

  # Json Serialization
  json_serializable: ^2.2.1

  # Generate QR Code Image
  qr_flutter: ^3.1.0
  qr: 1.2.0

  # Barcode Scan
  barcode_scan: 1.0.0

  # Flushbar instead of Snackbar for notifications
  flushbar: ^1.9.1

  # Secure Storage
  flutter_secure_storage: 3.3.1+1

  # dependency injection
  get_it: ^1.0.3

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

dev_dependencies:
  intl_translation: "^0.17.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/start-page/
    - assets/images/wallet-page/
  #  - lib/l10n/en.json
  #  - lib/l10n/zh.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
