name: exchangilymobileapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  pointycastle: ^1.0.1
  logger: ^0.7.0+2
  web3dart: ^1.2.1
  http: ^0.12.0+2
  font_awesome_flutter: 8.4.0
  provider: 3.1.0+1
  rxdart: ^0.21.0
  pattern_formatter: ^0.0.3
  path_provider: 1.4.2
  barcode_scan: 1.0.0
  keccak: ^1.0.3
  web_socket_channel: ^1.1.0
  json_serializable: ^2.2.1
  # Generate QR Code Image
  qr_flutter: ^3.1.0
  qr: 1.2.0
  image_picker_saver: 0.3.0
  image_gallery_saver: 1.2.2

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/start-page/
    - assets/images/wallet-page/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
