name: exchangilymobileapp
description: Decentralized Wallet App.

version: 2.0.0+59

environment:
  sdk: '>=2.3.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1



  # ----- Bitcoin -- Addresses -- Bip 


  # BIP 32
  # bip32: ^1.0.8
  # Bip39

  # Pointy Castle
  # pointycastle: ^1.0.1

  #bip39: ^1.0.3
  bs58check: ^1.0.1

  # bch address
  bitbox: ^0.0.1

  # Generate LTC and DOGE coin address
  bitcoin_flutter: ^2.0.1


  # ----- ICONS ---------

  # Cupertino Icons
  cupertino_icons: ^0.1.2

  # Font Awesome
  font_awesome_flutter: 8.8.0

  # ----- COMMUNICATION --------

  # Http
  http: ^0.12.0+2

  # Rxdart
  #rxdart: ^0.22.0

  # Web Sockets
  web_socket_channel: ^1.1.0

  # ----- SECURITY --------

  # Encrypt
  encrypt: ^3.3.0

  # Logger
  logger: ^0.6.0

  # Web 3 Dart
  web3dart: ^1.2.1


    # ----- ARCHITECTURE --------

  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.0.1

  # Pattern Formatter
  #pattern_formatter: ^1.0.0

  # Path Provider
  path_provider: 1.4.2

  # Random String
  random_string: ^2.0.1

  # Keccak
  keccak: ^1.0.3


  # Json Serialization
  # json_serializable: ^2.2.1

  # Generate QR Code Image
  qr_flutter: ^3.1.0
  qr: 1.2.0

  # Barcode Scan
  # barcode_scan: 3.0.1
  barcode_scan: ^2.0.2

  # Material icons
  material_design_icons_flutter: ^4.0.5345

  # Flushbar instead of Snackbar for notifications
  #flushbar: ^1.9.0
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master

  # decimal
  decimal: ^0.3.5

  # Dependency injection
  get_it: ^1.0.3

  # Device Preview
  device_preview:

  #webview_flutter
  #webview_flutter: ^0.3.19+4

  # rflutter Alert
  rflutter_alert: ^1.0.3

  # Shared Preferences
  shared_preferences: ^0.5.4+1

  # Loading animation
  shimmer: ^1.0.1

  # Sqflite
  sqflite: ^1.1.7

  # Path
  path: ^1.6.4

  # Build version
  package_info: 0.4.0+16

  # Pull to refresh
  pull_to_refresh: ^1.5.7

  # Flutter SVG
  flutter_svg: ^0.18.0

  # State Management
  stacked: ^1.7.6

  #flutter_beautiful_popup
  #flutter_beautiful_popup: ^1.5.0

  # Carousel
  flutter_swiper: ^1.1.6

  # validators
  validators: ^2.0.0+1

  # cached_network_image
  cached_network_image: ^2.0.0

  # fancy_bottom_navigation
  #fancy_bottom_navigation: ^0.3.2



  #gradient_text
  gradient_text: ^1.0.2

  #drop_cap_text
  drop_cap_text: ^1.0.7
  # launch the app in the app stores
  launch_review: ^2.0.0

  # To open web url's
  # ERROR
  # Flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.2\android\src\main\java\io\flutter\plugins\
  # urllauncher\WebViewActivity.java uses or overrides a deprecated API
  #url_launcher: ^5.6.0

  # video_player
  fijkplayer:

  #youtube_player
  youtube_player_flutter: ^7.0.0+7

  #flutter_html
  flutter_html: ^1.0.2

  #flutter_local_notifications
  flutter_local_notifications: ^1.4.4+4

  # #share
  # share: ^0.6.5+2

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  json_diff:
    git:
      url: https://github.com/google/dart-json_diff.git
      ref: master
  # To highlight new feature or how to use tuts
  showcaseview: ^0.1.6

  # Connectivity
  connectivity: ^0.4.3+1

  # Reactive
  observable_ish:

  # Pagination
  #pagination_view: ^1.0.3+2

  # Overlay notification
  overlay_support: ^1.0.5

  # Reload app
  flutter_phoenix: ^0.1.0



dev_dependencies:
  intl_translation: '^0.17.0'
  intl: ^0.16.0
  flutter_launcher_icons: '^0.7.3'

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # module:
  #   androidX: true
  #   androidPackage: my.package
  #   iosBundleIdentifier: my.package
  assets:
    - assets/images/start-page/
    - assets/images/img/
    - assets/images/wallet-page/
    - assets/images/otc/
    - assets/images/otc-campaign/
    - assets/pages/index.html
    - assets/images/shared/
    - assets/images/slider/
    - assets/images/bindpay/
flutter_icons:
  image_path: 'assets/images/launcher/mobile-icon-ios.png'

  android: true
  ios: true

fonts:
  - family: Roboto
    fonts:
      - asset: Roboto-Italic.ttf
      - asset: Roboto-normal.ttf
  #  - lib/l10n/en.json
  #  - lib/l10n/zh.json
